### ISSUE TITLE
Warn about public var that doesn't have a docstring

### ISSUE THREAD

**Issue by tatut** [borkdude/clj-kondo#259]
I don't know if it should be the default, but I think it would be useful to have a warning about public vars that don't have docstrings.

I find that I many times forget to use `defn-` or `^:private`, requiring those or a docstring for publics would be nice.

**Comment by borkdude** [comment]
from Slack: 
tatut [10:07 AM]
 I guess other linters check for this so it may not be a priority, but I still find the occasional misplaced docstring in my code, would be nice to warn about that
or more generally, superfluous discarded constant expressions
`(defn foo [bar] "misplaced docstring" ...code...)`
borkdude [10:12 AM]
 @tatut I think that overlaps with this issue. feel free to add it: https://github.com/borkdude/clj-kondo/issues/259
when I'm adding the `enhancement` label, it will probably be implemented. I can't promise when :slightly_smiling_face: (edited) 
tatut [10:13 AM]
 I think, the more general case isn’t overlapping… having constant expressions that are discarded
that we know can’t be for side effects
like `(defn foo [] 1 2 3)` the `1` and `2` are discarded and can’t side effect
borkdude [10:14 AM]
 missing docstring is probably something I will turn off by default, since not all people require this and it's not "wrong" to leave them out (arguably).
but a misplaced docstring is something I will probably turn on by default
discarding "useless" constant values is indeed a more general topic and doesn't only concern `def` and `defn` so that deserves a separate issue
maybe make two different issues for those things then

**Comment by borkdude** [comment]
@tatut This is now available as a custom linter using the new analysis data feature:

https://github.com/borkdude/clj-kondo/blob/master/analysis/README.md#missing-docstrings

**Comment by metasoarous** [comment]
@borkdude This is wonderful! We were just thinking about this. Is it possible to turn on via config? The linked example only shows this running from the command line, but we'd like it integrated in our editors.

**Comment by borkdude** [comment]
@metasoarous I'll consider this for a next release as an optional linter or level `:info`.

**Comment by metasoarous** [comment]
@borkdude Wonderful! Thank you!

**Comment by borkdude** [comment]
@tatut This is now implemented as an "optional" linter. See:

https://github.com/borkdude/clj-kondo/blob/master/doc/config.md#enable-optional-linters

Feedback welcome.
