### ISSUE TITLE
lint namespace alias consistency

### ISSUE THREAD

**Issue by borkdude** [borkdude/clj-kondo#561]
```
{:linters {:namespace-alias {foo.bar bar clojure.test t}}}
```
Warn when someone refers to `foo.bar` as something else than `bar`, etc.

Maybe the value in the config map should also be a map so it can take options, like: except in this namespace. But maybe the point of this linter should be that it's consistent without exceptions?

**Comment by borkdude** [comment]
@daveyarwood 

- Both warnings would be emitted when you would take some time to decide what is the agreed upon alias for `foo.bar`, `bar` in the starting comment.

- Linting these rules without any configuration would be complicated to implement and reason about. What would be "the other place" in the error message for example? Would you like to have errors when linting only two files which require the same lib with a different alias? Threshold? That would probably lead to a configuration to suppress undesired warnings which is more convoluted than the config in the starting comment?

**Comment by daveyarwood** [comment]
>  What would be "the other place" in the error message for example?

Is it possible to add warnings in both places? Like if namespace `bar` requires `foo :as f` and namespace `baz` requires `foo :as foo`, could we add warnings to the `foo` require in both files?

> Would you like to have errors when linting only two files which require the same lib with a different alias? Threshold? That would probably lead to a configuration to suppress undesired warnings which is more convoluted than the config in the starting comment?

I think this all depends on how opinionated clj-kondo wants to be. I could see the benefit of doing it either way. Personally, I like it when my linter is opinionated, can find a lot of problems and just throw them at me, vs. me having to put forth effort to tell it what to warn me about. But I could easily see other people getting frustrated with how "noisy" the linter output is out of the box, and needing to add a bunch of configuration to make it less noisy.

> You could implement something like this as a script on top of the analysis export, linting the entire project. But clj-kondo also has to work when linting only one file, without seeing the entire project first.

I think in the one file case, this rule would just do nothing, since it has to do with consistency across namespaces.

**Comment by borkdude** [comment]
> I think in the one file case, this rule would just do nothing, since it has to do with consistency across namespaces.

In that case there isn't really a benefit of having this inside the linter, if it has to see the entire project first. Then use the analysis export.

**Comment by borkdude** [comment]
@daveyarwood I wrote down some of the principles I've been using to build clj-kondo here:

https://github.com/borkdude/clj-kondo/blob/master/doc/dev.md#design-principles

I hope it adds to the understanding of trade-offs.

**Comment by borkdude** [comment]
@daveyarwood One other consideration. If the linter were to incrementally inform you of conflicts between aliases, you will still have to decide which one to choose for your project. That moment of choice will probably end up in the config (like the starting comment) anyway. So why not do it up front.

**Comment by daveyarwood** [comment]
That's a great point - I think that seals the deal for me. I think the idea is that in scenarios like these, we do have an idea about what "the right alias" should be for particular namespaces, so it's better that we explicitly specify that in the config.

Thanks for sticking with this debate and convincing me :)

**Comment by borkdude** [comment]
@daveyarwood What do you think: when you do not use an alias at all, should this rule bug you about it that you should use the recommended alias from the config? E.g. `fully.qualified.old-api/launch-missiles`?

**Comment by daveyarwood** [comment]
I don't think it should bug you in that case. I think there might be legitimate use cases for fully qualifying vars, so I would hesitate to have the linter complain about that, in general.

From namespace to namespace, I could see somebody having a preference for fully qualifying instead of using an alias.

Basically, I don't know if having a linter warning would provide much value, and it would probably be more likely to be annoying in the cases where you might want to fully qualify a var for reasons™.
