### ISSUE TITLE
Analyze `clojure.test/are`

### ISSUE THREAD

**Issue by thenonameguy** [borkdude/clj-kondo#596]
**Is your feature request related to a problem? Please describe.**
Sometimes we use `clojure.template/do-template` in place of `clojure.test/are` in our test suite since the former keeps line metadata. Sadly this macro is currently not yet handled by clj-kondo. The linting of the two macros can be shared, making this probably an easy enhancment.

**Describe the solution you'd like**
`clojure.template/do-template` gets linted, same as `clojure.test/are`.

**Comment by borkdude** [comment]
@thenonameguy There is currently not really an analysis for clojure.test/are other than that it's configured as `{:linters {:unresolved-symbol {:exclude [(clojure.test/are) (cljs.test/are)]}}}` which means: ignore all unresolved symbols in these macros. But I will consider supporting them with full analysis, since they are in core.

**Comment by borkdude** [comment]
Note to self:

`clojure.test/are` and `clojure.template/do-template` can take more than two symbols:

```
(clojure.test/are [a b c] (= a b c) 1 1 1, 2 2 2)
```

**Comment by borkdude** [comment]
@thenonameguy clojure.test/are is support with https://github.com/borkdude/clj-kondo/commit/b9c4ba5ec9c4dacf708f83459686ab1e75c3549b. 

However, analyzing `clojure.template/do-template` involves more work.
I'll have to include a built-in macroexpansion for it. I think this will be medium priority, since the usage of this macro is less common. However, if you use this macro in the limited way that clojure.test/are does, you can use `:lint-as` to make it work right now.

 See https://github.com/borkdude/clj-kondo/issues/603.

**Comment by thenonameguy** [comment]
Awesome, thanks! :)
