### ISSUE TITLE
Transitive dependency msgpack is vulnerable to CVE-2020-5234

### ISSUE THREAD

**Issue by taxonomic-blackfish** [borkdude/clj-kondo#762]
**version**

`2020.02.15`

**problem**

`clj-kondo` depends on `com.cognitect:transit-clj:0.8.313` which depends on `org.msgpack:msgpack:jar:0.6.12` which is vulnerable to `CVE-2020-5234`.

**expected behavior**

The library does not ship with vulnerable dependencies.

**Comment by borkdude** [comment]
@taxonomic-blackfish Are you also going to report this to transit-clj itself?

**Comment by retrogradeorbit** [comment]
MessagePack for *C# and Unity* before version 1.9.3 and 2.1.80 has a vulnerability where untrusted data can lead to DoS attack due to hash collisions and stack overflow.
https://nvd.nist.gov/vuln/detail/CVE-2020-5234

https://github.com/neuecc/MessagePack-CSharp/security/advisories/GHSA-7q36-4xx7-xcxf

**Comment by borkdude** [comment]
Ah, I see, so there is no problem?

**Comment by retrogradeorbit** [comment]
unsure where this message came from. Looks to be a stack overflow vulnerability in neuecc /
MessagePack-CSharp

**Comment by taxonomic-blackfish** [comment]
Yeah sorry, this should be closed because our automated tool told us the `jar` was vulnerable but this is a false positive. It's only C#.
