### ISSUE TITLE
Warn about usage of block `try` without `catch`

### ISSUE THREAD

**Issue by abogoyavlensky** [borkdude/clj-kondo#773]
It could be helpful to get warning when using `try` without `catch`. Because in that case `try` works simply as `do`:
```
user=> (try
  #_=>   (/ 1 0))
Execution error (ArithmeticException) at user/eval6793 (REPL:2).
Divide by zero
```

**Comment by borkdude** [comment]
We'll have to also check for `finally` because try + finally does sometimes happen without a catch I think. I'll ask around if try without catch and/or finally is indeed a code smell and then report back. I do think you're right.

**Comment by SevereOverfl0w** [comment]
Looks like java doesn't even compile if you do this: https://stackoverflow.com/questions/43441060/java-try-without-catch-and-catch-without-try

**Comment by borkdude** [comment]
> alexmiller no legit use I'm aware of

**Comment by borkdude** [comment]
Note that the most recent patch, clj-1472-5,  for CLJ-1472 has a `try` without a catch. As this may affect how the bytecode is generated, it may have a purpose after all. 

https://clojure.atlassian.net/browse/CLJ-1472

cc @puredanger

**Comment by borkdude** [comment]
Dump from Slack thread:

10h
borkdude  
Why is there a try inside a try, is the outer try still doing anything? 
Remember that we talked recently about there being no legit use case for a try without a catch / finally for a linter feature? :slightly_smiling_face: I wonder if this matter for the bytecode? (edited) 

7h
alexmiller  so, it is important in this case because of how the body of the try gets lifted into a function, but it should not matter in 99.999% of normal cases.
7h
alexmiller  what was happening before is that the locking macro expanded to a try not in the tail position, and that lifts the try body into a function (around which you can do catch/finally kinds of stuff), which means the monitorenter was in the original body and the monitorexit was in the lifted function (with the lockee as a closed over field in the function object). because these are in different methods and in a field, which gets loaded and cleared due to locals clearing, the graal analyzers can't connect that the monitorexit is attached to the monitorenter and it looks unbalanced.
7h
alexmiller  the outer let in the new locking macro evaluates the lock object, that goes into the the next try block. the inner let puts it in a local, which will be not cleared due to the outer try (as it might be needed if there is a finally), the lock object then ends up on the stack for both enter and exit.
7h
alexmiller  so the outer try here influences locals clearing just to make the lockee tracking easier for the graal analyzer.
7h
alexmiller  needless to say, this is super subtle
7m
bherrmann  I recommend copy/pasting that explanation right above the try block.
<1m
borkdude  yeah, adding a comment seems good to me. maybe the linter feature will still be good because in 99.999% of the cases forgetting a catch is probably something in the category of silly errors (and the rule can be disabled)

**Comment by borkdude** [comment]
I added the clj-together label. If this project gets funded by Clojurists Together I can do it during the funding period.
